import { EditorView } from "@codemirror/view";

export const THEME_IDS = [
  "zapret",
  "dracula",
  "oneDark",
  "nord",
  "monokai",
  "tokyoNight",
  "catppuccin",
  "gruvbox",
  "solarizedLight",
  "githubLight",
] as const;

export type ThemeId = (typeof THEME_IDS)[number];

type TokenStyle =
  | string
  | {
      color: string;
      fontWeight?: number;
      fontStyle?: string;
      background?: string;
      borderRadius?: string;
      textDecoration?: string;
    };

type ThemeSpec = {
  id: ThemeId;
  label: string;
  dark: boolean;
  editor: string;
  text: string;
  gutter: string;
  gutterFg: string;
  activeLine: string;
  activeGutter: string;
  selection: string;
  caret: string;
  tooltip: string;
  tooltipBorder: string;
  selectedCompletion: string;
  selectedCompletionFg: string;
  matching: string;
  error: string;
  warn: string;
  info: string;
  tokens: Record<string, TokenStyle>;
};

function flags(p: {
  comment: string;
  keyword: string;
  variable: string;
  string: string;
  continuation: TokenStyle;
  operator: string;
  number: string;
  path: string;
  exe: TokenStyle;
  control: TokenStyle;
  windivert: string;
  filter: string;
  host: string;
  ipset: string;
  desync: string;
  fake: string;
  split: string;
  dup: string;
  orig: string;
  http: string;
  misc: string;
  linux: TokenStyle;
  mode: string;
  proto: string;
  fooling: string;
  marker: string;
  bool: string;
  hex: string;
  junk: TokenStyle;
  text: string;
}): ThemeSpec["tokens"] {
  return {
    comment: { color: p.comment, fontStyle: "italic" },
    keyword: p.keyword,
    variable: p.variable,
    string: p.string,
    continuation: p.continuation,
    operator: p.operator,
    number: p.number,
    port: p.number,
    path: p.path,
    exe: p.exe,
    "flag-control": p.control,
    "flag-windivert": { color: p.windivert, fontWeight: 700 },
    "flag-filter": { color: p.filter, fontWeight: 700 },
    "flag-hostlist": { color: p.host, fontWeight: 700 },
    "flag-ipset": { color: p.ipset, fontWeight: 700 },
    "flag-desync": { color: p.desync, fontWeight: 700 },
    "flag-fake": { color: p.fake, fontWeight: 700 },
    "flag-split": { color: p.split, fontWeight: 700 },
    "flag-dup": { color: p.dup, fontWeight: 700 },
    "flag-orig": { color: p.orig, fontWeight: 700 },
    "flag-http": { color: p.http, fontWeight: 700 },
    "flag-misc": p.misc,
    "flag-linux": p.linux,
    "flag-unknown": typeof p.junk === "string" ? { color: p.junk } : p.junk,
    "value-mode": p.mode,
    "value-proto": p.proto,
    "value-fooling": p.fooling,
    "value-marker": p.marker,
    "value-bool": p.bool,
    hex: p.hex,
    junk: p.junk,
    text: p.text,
  };
}

const specs: ThemeSpec[] = [
  {
    id: "zapret",
    label: "Zapret",
    dark: true,
    editor: "#0c1220",
    text: "#d7e0ea",
    gutter: "#0c1220",
    gutterFg: "#9aa8b8",
    activeLine: "rgba(46, 230, 198, 0.05)",
    activeGutter: "#2ee6c6",
    selection: "rgba(255, 176, 32, 0.22)",
    caret: "#ffb020",
    tooltip: "#121826",
    tooltipBorder: "rgba(46, 230, 198, 0.18)",
    selectedCompletion: "rgba(255, 176, 32, 0.16)",
    selectedCompletionFg: "#ffe7b3",
    matching: "rgba(46, 230, 198, 0.18)",
    error: "#ff5c7a",
    warn: "#ffb020",
    info: "#2ee6c6",
    tokens: flags({
      comment: "#6d7d8f",
      keyword: "#c792ea",
      variable: "#7ee0ff",
      string: "#c8f0c0",
      continuation: { color: "#ffe566", fontWeight: 800, background: "rgba(255, 229, 102, 0.12)", borderRadius: "3px" },
      operator: "#8ea0b5",
      number: "#ffd27a",
      path: "#9ee37d",
      exe: { color: "#ffffff", fontWeight: 700 },
      control: { color: "#ffe566", fontWeight: 800, background: "rgba(255, 229, 102, 0.14)", borderRadius: "3px" },
      windivert: "#2ee6c6",
      filter: "#5b9dff",
      host: "#3ddc84",
      ipset: "#86e36a",
      desync: "#ffb020",
      fake: "#ff5cad",
      split: "#ff8a4c",
      dup: "#f0a3ff",
      orig: "#9ad0ff",
      http: "#7ad4ff",
      misc: "#b8c4d4",
      linux: { color: "#8b9cb0", fontStyle: "italic" },
      mode: "#ffc14d",
      proto: "#7ec8ff",
      fooling: "#ff8ad4",
      marker: "#ff9a62",
      bool: "#ffe7b3",
      hex: "#c9b6ff",
      junk: {
        color: "#ffdce3",
        background: "rgba(255, 92, 122, 0.22)",
        borderRadius: "3px",
        textDecoration: "wavy underline #ff5c7a",
      },
      text: "#c5d0db",
    }),
  },
  {
    id: "dracula",
    label: "Dracula",
    dark: true,
    editor: "#282a36",
    text: "#f8f8f2",
    gutter: "#282a36",
    gutterFg: "#6272a4",
    activeLine: "#44475a55",
    activeGutter: "#f8f8f2",
    selection: "#44475a",
    caret: "#f8f8f2",
    tooltip: "#21222c",
    tooltipBorder: "#6272a4",
    selectedCompletion: "#44475a",
    selectedCompletionFg: "#f8f8f2",
    matching: "#44475a",
    error: "#ff5555",
    warn: "#ffb86c",
    info: "#8be9fd",
    tokens: flags({
      comment: "#6272a4",
      keyword: "#ff79c6",
      variable: "#f8f8f2",
      string: "#f1fa8c",
      continuation: { color: "#ffb86c", fontWeight: 700 },
      operator: "#ff79c6",
      number: "#bd93f9",
      path: "#50fa7b",
      exe: { color: "#f8f8f2", fontWeight: 700 },
      control: { color: "#ffb86c", fontWeight: 700 },
      windivert: "#8be9fd",
      filter: "#8be9fd",
      host: "#50fa7b",
      ipset: "#50fa7b",
      desync: "#f1fa8c",
      fake: "#ff79c6",
      split: "#ffb86c",
      dup: "#bd93f9",
      orig: "#8be9fd",
      http: "#8be9fd",
      misc: "#f8f8f2",
      linux: { color: "#6272a4", fontStyle: "italic" },
      mode: "#f1fa8c",
      proto: "#8be9fd",
      fooling: "#ff79c6",
      marker: "#ffb86c",
      bool: "#bd93f9",
      hex: "#bd93f9",
      junk: { color: "#ff5555", textDecoration: "wavy underline #ff5555" },
      text: "#f8f8f2",
    }),
  },
  {
    id: "oneDark",
    label: "One Dark",
    dark: true,
    editor: "#282c34",
    text: "#abb2bf",
    gutter: "#282c34",
    gutterFg: "#5c6370",
    activeLine: "#2c313c",
    activeGutter: "#abb2bf",
    selection: "#3e4451",
    caret: "#528bff",
    tooltip: "#21252b",
    tooltipBorder: "#181a1f",
    selectedCompletion: "#2c313a",
    selectedCompletionFg: "#ffffff",
    matching: "#3e4451",
    error: "#e06c75",
    warn: "#e5c07b",
    info: "#61afef",
    tokens: flags({
      comment: "#5c6370",
      keyword: "#c678dd",
      variable: "#e06c75",
      string: "#98c379",
      continuation: { color: "#d19a66", fontWeight: 700 },
      operator: "#56b6c2",
      number: "#d19a66",
      path: "#98c379",
      exe: { color: "#abb2bf", fontWeight: 700 },
      control: { color: "#d19a66", fontWeight: 700 },
      windivert: "#56b6c2",
      filter: "#61afef",
      host: "#98c379",
      ipset: "#98c379",
      desync: "#e5c07b",
      fake: "#c678dd",
      split: "#d19a66",
      dup: "#c678dd",
      orig: "#61afef",
      http: "#61afef",
      misc: "#abb2bf",
      linux: { color: "#5c6370", fontStyle: "italic" },
      mode: "#e5c07b",
      proto: "#61afef",
      fooling: "#c678dd",
      marker: "#d19a66",
      bool: "#56b6c2",
      hex: "#c678dd",
      junk: { color: "#e06c75", textDecoration: "wavy underline #e06c75" },
      text: "#abb2bf",
    }),
  },
  {
    id: "nord",
    label: "Nord",
    dark: true,
    editor: "#2e3440",
    text: "#d8dee9",
    gutter: "#2e3440",
    gutterFg: "#4c566a",
    activeLine: "#3b4252",
    activeGutter: "#eceff4",
    selection: "#434c5e",
    caret: "#d8dee9",
    tooltip: "#3b4252",
    tooltipBorder: "#4c566a",
    selectedCompletion: "#434c5e",
    selectedCompletionFg: "#eceff4",
    matching: "#4c566a",
    error: "#bf616a",
    warn: "#ebcb8b",
    info: "#88c0d0",
    tokens: flags({
      comment: "#616e88",
      keyword: "#81a1c1",
      variable: "#d8dee9",
      string: "#a3be8c",
      continuation: { color: "#ebcb8b", fontWeight: 700 },
      operator: "#81a1c1",
      number: "#b48ead",
      path: "#a3be8c",
      exe: { color: "#eceff4", fontWeight: 700 },
      control: { color: "#ebcb8b", fontWeight: 700 },
      windivert: "#88c0d0",
      filter: "#81a1c1",
      host: "#a3be8c",
      ipset: "#a3be8c",
      desync: "#ebcb8b",
      fake: "#b48ead",
      split: "#d08770",
      dup: "#b48ead",
      orig: "#88c0d0",
      http: "#8fbcbb",
      misc: "#d8dee9",
      linux: { color: "#616e88", fontStyle: "italic" },
      mode: "#ebcb8b",
      proto: "#88c0d0",
      fooling: "#b48ead",
      marker: "#d08770",
      bool: "#81a1c1",
      hex: "#b48ead",
      junk: { color: "#bf616a", textDecoration: "wavy underline #bf616a" },
      text: "#d8dee9",
    }),
  },
  {
    id: "monokai",
    label: "Monokai",
    dark: true,
    editor: "#272822",
    text: "#f8f8f2",
    gutter: "#272822",
    gutterFg: "#75715e",
    activeLine: "#3e3d32",
    activeGutter: "#cfcfc2",
    selection: "#49483e",
    caret: "#f8f8f0",
    tooltip: "#1e1f1c",
    tooltipBorder: "#49483e",
    selectedCompletion: "#49483e",
    selectedCompletionFg: "#f8f8f2",
    matching: "#49483e",
    error: "#f92672",
    warn: "#e6db74",
    info: "#66d9ef",
    tokens: flags({
      comment: "#75715e",
      keyword: "#f92672",
      variable: "#f8f8f2",
      string: "#e6db74",
      continuation: { color: "#fd971f", fontWeight: 700 },
      operator: "#f92672",
      number: "#ae81ff",
      path: "#a6e22e",
      exe: { color: "#f8f8f2", fontWeight: 700 },
      control: { color: "#fd971f", fontWeight: 700 },
      windivert: "#66d9ef",
      filter: "#66d9ef",
      host: "#a6e22e",
      ipset: "#a6e22e",
      desync: "#e6db74",
      fake: "#f92672",
      split: "#fd971f",
      dup: "#ae81ff",
      orig: "#66d9ef",
      http: "#66d9ef",
      misc: "#f8f8f2",
      linux: { color: "#75715e", fontStyle: "italic" },
      mode: "#e6db74",
      proto: "#66d9ef",
      fooling: "#f92672",
      marker: "#fd971f",
      bool: "#ae81ff",
      hex: "#ae81ff",
      junk: { color: "#f92672", textDecoration: "wavy underline #f92672" },
      text: "#f8f8f2",
    }),
  },
  {
    id: "tokyoNight",
    label: "Tokyo Night",
    dark: true,
    editor: "#1a1b26",
    text: "#c0caf5",
    gutter: "#1a1b26",
    gutterFg: "#565f89",
    activeLine: "#24283b",
    activeGutter: "#c0caf5",
    selection: "#33467c",
    caret: "#c0caf5",
    tooltip: "#16161e",
    tooltipBorder: "#3b4261",
    selectedCompletion: "#283457",
    selectedCompletionFg: "#c0caf5",
    matching: "#3b4261",
    error: "#f7768e",
    warn: "#e0af68",
    info: "#7dcfff",
    tokens: flags({
      comment: "#565f89",
      keyword: "#bb9af7",
      variable: "#c0caf5",
      string: "#9ece6a",
      continuation: { color: "#ff9e64", fontWeight: 700 },
      operator: "#89ddff",
      number: "#ff9e64",
      path: "#9ece6a",
      exe: { color: "#c0caf5", fontWeight: 700 },
      control: { color: "#ff9e64", fontWeight: 700 },
      windivert: "#7dcfff",
      filter: "#7aa2f7",
      host: "#9ece6a",
      ipset: "#9ece6a",
      desync: "#e0af68",
      fake: "#bb9af7",
      split: "#ff9e64",
      dup: "#bb9af7",
      orig: "#7aa2f7",
      http: "#7dcfff",
      misc: "#a9b1d6",
      linux: { color: "#565f89", fontStyle: "italic" },
      mode: "#e0af68",
      proto: "#7dcfff",
      fooling: "#bb9af7",
      marker: "#ff9e64",
      bool: "#7aa2f7",
      hex: "#bb9af7",
      junk: { color: "#f7768e", textDecoration: "wavy underline #f7768e" },
      text: "#c0caf5",
    }),
  },
  {
    id: "catppuccin",
    label: "Catppuccin Mocha",
    dark: true,
    editor: "#1e1e2e",
    text: "#cdd6f4",
    gutter: "#1e1e2e",
    gutterFg: "#6c7086",
    activeLine: "#313244",
    activeGutter: "#cdd6f4",
    selection: "#45475a",
    caret: "#f5e0dc",
    tooltip: "#181825",
    tooltipBorder: "#45475a",
    selectedCompletion: "#313244",
    selectedCompletionFg: "#cdd6f4",
    matching: "#45475a",
    error: "#f38ba8",
    warn: "#f9e2af",
    info: "#89dceb",
    tokens: flags({
      comment: "#6c7086",
      keyword: "#cba6f7",
      variable: "#cdd6f4",
      string: "#a6e3a1",
      continuation: { color: "#fab387", fontWeight: 700 },
      operator: "#89dceb",
      number: "#fab387",
      path: "#a6e3a1",
      exe: { color: "#cdd6f4", fontWeight: 700 },
      control: { color: "#fab387", fontWeight: 700 },
      windivert: "#94e2d5",
      filter: "#89b4fa",
      host: "#a6e3a1",
      ipset: "#a6e3a1",
      desync: "#f9e2af",
      fake: "#f5c2e7",
      split: "#fab387",
      dup: "#cba6f7",
      orig: "#89b4fa",
      http: "#89dceb",
      misc: "#bac2de",
      linux: { color: "#6c7086", fontStyle: "italic" },
      mode: "#f9e2af",
      proto: "#89dceb",
      fooling: "#f5c2e7",
      marker: "#fab387",
      bool: "#cba6f7",
      hex: "#cba6f7",
      junk: { color: "#f38ba8", textDecoration: "wavy underline #f38ba8" },
      text: "#cdd6f4",
    }),
  },
  {
    id: "gruvbox",
    label: "Gruvbox Dark",
    dark: true,
    editor: "#282828",
    text: "#ebdbb2",
    gutter: "#282828",
    gutterFg: "#928374",
    activeLine: "#3c3836",
    activeGutter: "#ebdbb2",
    selection: "#504945",
    caret: "#ebdbb2",
    tooltip: "#1d2021",
    tooltipBorder: "#504945",
    selectedCompletion: "#3c3836",
    selectedCompletionFg: "#ebdbb2",
    matching: "#504945",
    error: "#fb4934",
    warn: "#fabd2f",
    info: "#83a598",
    tokens: flags({
      comment: "#928374",
      keyword: "#fb4934",
      variable: "#ebdbb2",
      string: "#b8bb26",
      continuation: { color: "#fe8019", fontWeight: 700 },
      operator: "#fe8019",
      number: "#d3869b",
      path: "#b8bb26",
      exe: { color: "#ebdbb2", fontWeight: 700 },
      control: { color: "#fe8019", fontWeight: 700 },
      windivert: "#8ec07c",
      filter: "#83a598",
      host: "#b8bb26",
      ipset: "#b8bb26",
      desync: "#fabd2f",
      fake: "#d3869b",
      split: "#fe8019",
      dup: "#d3869b",
      orig: "#83a598",
      http: "#8ec07c",
      misc: "#ebdbb2",
      linux: { color: "#928374", fontStyle: "italic" },
      mode: "#fabd2f",
      proto: "#83a598",
      fooling: "#d3869b",
      marker: "#fe8019",
      bool: "#8ec07c",
      hex: "#d3869b",
      junk: { color: "#fb4934", textDecoration: "wavy underline #fb4934" },
      text: "#ebdbb2",
    }),
  },
  {
    id: "solarizedLight",
    label: "Solarized Light",
    dark: false,
    editor: "#fdf6e3",
    text: "#657b83",
    gutter: "#eee8d5",
    gutterFg: "#93a1a1",
    activeLine: "#eee8d5",
    activeGutter: "#586e75",
    selection: "#d3cbb7",
    caret: "#586e75",
    tooltip: "#eee8d5",
    tooltipBorder: "#93a1a1",
    selectedCompletion: "#d3cbb7",
    selectedCompletionFg: "#073642",
    matching: "#d3cbb7",
    error: "#dc322f",
    warn: "#b58900",
    info: "#268bd2",
    tokens: flags({
      comment: "#93a1a1",
      keyword: "#859900",
      variable: "#268bd2",
      string: "#2aa198",
      continuation: { color: "#cb4b16", fontWeight: 700 },
      operator: "#657b83",
      number: "#d33682",
      path: "#859900",
      exe: { color: "#073642", fontWeight: 700 },
      control: { color: "#cb4b16", fontWeight: 700 },
      windivert: "#2aa198",
      filter: "#268bd2",
      host: "#859900",
      ipset: "#859900",
      desync: "#b58900",
      fake: "#d33682",
      split: "#cb4b16",
      dup: "#6c71c4",
      orig: "#268bd2",
      http: "#2aa198",
      misc: "#657b83",
      linux: { color: "#93a1a1", fontStyle: "italic" },
      mode: "#b58900",
      proto: "#268bd2",
      fooling: "#d33682",
      marker: "#cb4b16",
      bool: "#6c71c4",
      hex: "#6c71c4",
      junk: { color: "#dc322f", textDecoration: "wavy underline #dc322f" },
      text: "#657b83",
    }),
  },
  {
    id: "githubLight",
    label: "GitHub Light",
    dark: false,
    editor: "#ffffff",
    text: "#1f2328",
    gutter: "#ffffff",
    gutterFg: "#8c959f",
    activeLine: "#eaeef2",
    activeGutter: "#1f2328",
    selection: "#b6e3ff",
    caret: "#1f2328",
    tooltip: "#ffffff",
    tooltipBorder: "#d0d7de",
    selectedCompletion: "#ddf4ff",
    selectedCompletionFg: "#1f2328",
    matching: "#d0d7de",
    error: "#cf222e",
    warn: "#9a6700",
    info: "#0969da",
    tokens: flags({
      comment: "#6e7781",
      keyword: "#cf222e",
      variable: "#953800",
      string: "#0a3069",
      continuation: { color: "#cf222e", fontWeight: 700 },
      operator: "#1f2328",
      number: "#0550ae",
      path: "#0a3069",
      exe: { color: "#1f2328", fontWeight: 700 },
      control: { color: "#cf222e", fontWeight: 700 },
      windivert: "#0550ae",
      filter: "#0550ae",
      host: "#116329",
      ipset: "#116329",
      desync: "#9a6700",
      fake: "#8250df",
      split: "#953800",
      dup: "#8250df",
      orig: "#0550ae",
      http: "#0550ae",
      misc: "#1f2328",
      linux: { color: "#6e7781", fontStyle: "italic" },
      mode: "#9a6700",
      proto: "#0550ae",
      fooling: "#8250df",
      marker: "#953800",
      bool: "#0550ae",
      hex: "#8250df",
      junk: { color: "#cf222e", textDecoration: "wavy underline #cf222e" },
      text: "#1f2328",
    }),
  },
];

export const THEMES = specs.map(({ id, label, dark }) => ({ id, label, dark }));

const cache = new Map<ThemeId, ReturnType<typeof EditorView.theme>>();

function styleOf(value: TokenStyle) {
  return typeof value === "string" ? { color: value } : value;
}

export function createEditorTheme(id: ThemeId) {
  const cached = cache.get(id);
  if (cached) return cached;
  const spec = specs.find((item) => item.id === id) ?? specs[0]!;
  const tokenStyles = Object.fromEntries(
    Object.entries(spec.tokens).map(([name, value]) => [`.tok-${name}`, styleOf(value)]),
  );
  const theme = EditorView.theme(
    {
      "&": {
        backgroundColor: spec.editor,
        color: spec.text,
        fontSize: "inherit",
        height: "100%",
      },
      ".cm-scroller": {
        fontFamily: '"IBM Plex Mono", "JetBrains Mono", ui-monospace, monospace',
        lineHeight: "1.65",
      },
      ".cm-content": {
        caretColor: spec.caret,
        padding: "12px 0",
      },
      ".cm-gutters": {
        backgroundColor: spec.gutter,
        border: "none",
        color: spec.gutterFg,
        opacity: "1",
      },
      ".cm-lineNumbers": {
        color: spec.gutterFg,
        opacity: "1",
      },
      ".cm-lineNumbers .cm-gutterElement": {
        padding: "0 12px 0 16px",
        color: spec.gutterFg,
        opacity: "1",
      },
      ".cm-activeLine": {
        backgroundColor: spec.activeLine,
      },
      ".cm-activeLineGutter": {
        backgroundColor: spec.gutter,
        color: spec.activeGutter,
        opacity: "1",
      },
      ".cm-selectionBackground, &.cm-focused .cm-selectionBackground": {
        backgroundColor: `${spec.selection} !important`,
      },
      ".cm-cursor": {
        borderLeftColor: spec.caret,
        borderLeftWidth: "2px",
      },
      ".cm-matchingBracket": {
        backgroundColor: spec.matching,
      },
      ".cm-tooltip": {
        backgroundColor: spec.tooltip,
        border: `1px solid ${spec.tooltipBorder}`,
        color: spec.text,
        borderRadius: "10px",
      },
      ".cm-tooltip-autocomplete ul li[aria-selected]": {
        background: spec.selectedCompletion,
        color: spec.selectedCompletionFg,
      },
      ".cm-panels": {
        backgroundColor: spec.tooltip,
        color: spec.text,
        borderTop: `1px solid ${spec.tooltipBorder}`,
      },
      ".cm-textfield": {
        backgroundColor: spec.editor === "transparent" ? "#101828" : spec.editor,
        border: `1px solid ${spec.tooltipBorder}`,
        color: spec.text,
        borderRadius: "8px",
      },
      ".cm-button": {
        background: spec.activeLine,
        border: `1px solid ${spec.tooltipBorder}`,
        color: spec.text,
        borderRadius: "8px",
      },
      ".cm-tooltip-lint": {
        padding: "0",
        margin: "0",
      },
      ".cm-diagnostic": {
        borderLeft: "none",
        margin: "0",
        padding: "10px 12px",
        borderRadius: "0",
      },
      ".cm-diagnostic-error": { backgroundColor: `${spec.error}2e` },
      ".cm-diagnostic-warning": { backgroundColor: `${spec.warn}2e` },
      ".cm-diagnostic-info": { backgroundColor: `${spec.info}2e` },
      ".cm-lintRange-error": {
        backgroundImage: "none",
        textDecoration: `wavy underline ${spec.error}`,
      },
      ".cm-lintRange-warning": {
        backgroundImage: "none",
        textDecoration: `wavy underline ${spec.warn}`,
      },
      ".cm-lintRange-info": {
        backgroundImage: "none",
        textDecoration: `wavy underline ${spec.info}`,
      },
      ".cm-strategy-mark": {
        width: "4px",
        marginLeft: "4px",
      },
      ...tokenStyles,
    },
    { dark: spec.dark },
  );
  cache.set(id, theme);
  return theme;
}

export function isThemeId(value: string): value is ThemeId {
  return THEME_IDS.includes(value as ThemeId);
}
